name: Firebase Hosting CI

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode Firebase Service Account Key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > $HOME/firebase-key.json

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project seewonschool-f47ca --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
